### ISSUE TITLE
Strange arm init pose

### ISSUE THREAD

**Issue by 130s** [tork-a/spur#26]
Robot starts with this initial pose. This didn't happen a week ago AFAIR.

![spur_strange_arm_initpose_gazebo](https://cloud.githubusercontent.com/assets/1840401/7507103/62de4116-f4a5-11e4-8b83-e47bfb8badc4.png)

```
$ dpkg -p ros-indigo-spur-gazebo|grep Ver
Version: 0.1.1-0trusty-20150501-111006-0700
```
Since this happens using DEB, I suspect changes in upstream causes this.

**Comment by 534o** [comment]
it works for me, with following settings (I could get 111006 version)
```
$ dpkg -l| grep spur
ii  ros-indigo-spur                                       0.1.1-0trusty-20150501-0439-+0000                   amd64        The spur package
ii  ros-indigo-spur-controller                            0.1.1-0trusty-20150501-0435-+0000                   amd64        The spur_controller package
ii  ros-indigo-spur-description                           0.1.1-0trusty-20150430-1747-+0000                   amd64        The spur_description package
ii  ros-indigo-spur-gazebo                                0.1.1-0trusty-20150501-0206-+0000                   amd64        The spur_description package
```
it seems spur-gazebo did not depends on any other spur-* pakcage so installing spur-gazebo is not sufficient
```
$ aptitude show ros-indigo-spur-gazebo 
Package: ros-indigo-spur-gazebo          
New: yes
State: installed
Automatically installed: no
Version: 0.1.1-0trusty-20150501-0206-+0000
Priority: extra
Section: misc
Maintainer: TORK <dev@opensource-robotics.tokyo.jp>
Architecture: amd64
Uncompressed Size: 90.1 k
Depends: ros-indigo-gazebo-ros, ros-indigo-gazebo-ros-control, ros-indigo-robot-state-publisher
Conflicts: ros-indigo-spur-gazebo
Description: The spur_description package
 
Homepage: http://wiki.ros.org/spur_gazebo
```
any time you have trouble, please check following setting, checking deb version is not enough, mostly thy type of error comes from any confusion of ros package path. also if you had habit of  changed /opt/ros/indigo manually, you'd better to use `apt-get install --reinstall ros-indigo-spur-*` to reinstall software.

also model is defined in _description package, so we'd check not only _gazebo package, but check _description package.
```
$ echo $ROS_PACKAGE_PATH
/opt/ros/indigo/share:/opt/ros/indigo/stacks
$ rosversion spur_gazebo
0.1.1
$ rosversion spur_description
0.1.1
$ rosversion spur_controller
0.1.1
```

but as we're still debugging on this package, source codes may change until next release, so I think we should check deb package after we have released complete version. until then, we should focus on source tree, not deb release. I think it is always better to focus on small problem as much as possible. try to solve any problem one by one since we, human is not mede for multi-task thing.

Also gazebo has huge user groups and it release policy is very conservative, specially for package in ros, they kept old release and not change anything. so it is very unlikely to suspect upstream change, specially this type of robot, which we did not have any special mechanism. So before we suspect upstream change, we'd check our environment.

**Comment by 130s** [comment]
After re-installing `ros-indigo-*` and `ros-indigo-spur`, this issue is gone. 

I knew I screwed up my Trusty (when [trying to install ROS Jade desktop-full due to Gazebo version](http://answers.ros.org/question/208334/gazebo-version-collides-bw-indigo-and-jade/)).

> we're still debugging on this package, source codes may change until next release, so I think we should check deb package after we have released complete version. 

Got it.
